export const FETCH_API = 'FETCH_API';
export const SET_FILTERED_THERAPISTS = 'SET_FILTERED_THERAPISTS';

// Auth actions
export const SET_USERS_CONTEXT = 'SET_USERS_CONTEXT'
export const CLEAR_USERS_CONTEXT = 'CLEAR_USERS_CONTEXT'